# file: postgresql/tasks/install_yum.yml

# The standard ca-certs are needed because  without them apt_key will fail to
# validate www.postgresql.org (or probably any other source).

  - block:
      - name: PostgreSQL | Make sure the CA certificates are available
        dnf:
          name: ca-certificates
          state: present

      - name: PostgreSQL | Add PostgreSQL repository
        dnf:
          name: "{{ postgresql_dnf_repository_url }}"
          state: present

      - name: PostgreSQL | Make sure the dependencies are installed
        dnf:
         name: "{{ item }}"
         state: present
        with_items: ["python-psycopg2", "python-pycurl", "glibc-common","libselinux-python"]

      - name: PostgreSQL | Install PostgreSQL
        dnf:
          name: "{{ item }}"
          state: present
        environment: "{{ postgresql_env }}"
        with_items:
          - "postgresql{{ postgresql_version_terse }}-server"
          - "postgresql{{ postgresql_version_terse }}"
          - "postgresql{{ postgresql_version_terse }}-contrib"

      - name: PostgreSQL | PGTune
        dnf:
          name: pgtune
          state: present
        environment: "{{ postgresql_env }}"
        when: postgresql_pgtune

