# file: postgresql/tasks/main.yml

- include: install.yml
- include: extensions.yml
- include: configure.yml
- include: users.yml
- include: databases.yml
- include: users_priv.yml
- include: monit.yml
  when: monit_protection is defined and monit_protection == true
